### ISSUE TITLE
jira-post-fetch-hook doesn't handle branch names including '/'

### ISSUE THREAD

**Issue by trentm** [trentm/molybdenum#15]
A ref 'refs/heads/foo/bar' is parsed as branch name 'bar' instead of the correct 'foo/bar'.
This causes problems for the whitelist/blacklist matching.

**Comment by trentm** [comment]
@rmustacc This is the problem that mo.jo was hitting with the joyent/nginx repo branch names.

**Comment by rmustacc** [comment]
Thanks @trentm!
